package constant

const (
	OrderServerLogFileName             = "orderServer"
	PayoutServerLogFileName            = "payoutServer"
	MerchantServerLogFileName          = "merchantServer"
	ChannelDepartTradeTypeLogFileName  = "channelDepartTradeTypeServer"
	ChannelConfigLogFileName           = "channelConfigServer"
	FirstPayLogFileName                = "firstPayServer"
	SevenEightPayLogFileName           = "seveneightPayServer"
	AbcPayLogFileName                  = "abcPayServer"
	AmarquickPayLogFileName            = "amarquickPayServer"
	ZPayLogFileName                    = "zPayServer"
	FirstPayCallBackLogFileName        = "firstPayCallBackServer"
	ZPayCallBackLogFileName            = "zPayCallBackServer"
	SevenEightPayCallBackLogFileName   = "sevenEightPayCallBackServer"
	AbcPayCallBackLogFileName          = "abcPayCallBackServer"
	AmarquickPayCallBackLogFileName    = "amarquickPayCallBackServer"
	OrderServerJobLogFileName          = "orderServerJob"
	MerchantProjectCurrencyLogFileName = "merchantProjectCurrencyServerJob"
	PayoutServerJobLogFileName         = "payoutServerJob"
	PayoutAuditServerJobLogFileName    = "payoutAuditServerJob"
	JobsServerLogFileName              = "jobsServer"
	CrondServerLogFileName             = "crondServer"
	StatisticServerLogFileName         = "statisticServer"
	FynzonpayLogFileName               = "fynzonpayServer"
	FynzonPayCallBackLogFileName       = "fynzonpayCallBackServer"
	MyPayLogFileName                   = "myPayServer"
	MyPayCallBackLogFileName           = "myPayCallBackServer"
	HaodaPayLogFileName                = "haodapayServer"
	HaodaPayCallBackLogFileName        = "haodapayCallBackServer"
)
